name: Test PR & Periodic

on:
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'LICENSE'
     - '.gitlab-ci.yml.example'
     - '.gitignore'
  schedule:
    # only run once a week to show the action is working and preserve as much energy as possible
    # Reason being that we pull our ML model and this could have changed in the meantime
    - cron: '22 4 * * 6'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v4
        with:
          path: .

      - name: Initialize Energy Estimation
        uses: ./
        with:
          task: start-measurement
          project: "Eco CI"
          machine: "ubuntu-latest"
          tags: "CI/CD,Test PR & Periodic-Workflow"
          gmt-api-token: ${{ secrets.GMT_API_TOKEN }}

      - name: working step
        continue-on-error: true
        run: |
          timeout 2s ls -alhR / || true

      - name: Final Measurement no label
        uses: ./
        with:
          task: get-measurement


      - name: Eco CI Energy Estimation
        uses: ./
        with:
          task: display-results
          pr-comment: true

      - name: Validate power values
        shell: bash
        run: |
          set -e
          min=1.75
          max=5.60

          total_power=$(grep "<td>Total Run</td>" /tmp/eco-ci/output.txt | awk -F'</td><td>' '{print $4}')

          awk -v p="$total_power" -v min="$min" -v max="$max" '
          BEGIN {
            if (p ~ /^[0-9.]+$/) {
              printf "Total power: %.2f\n", p
              if (p > min && p < max) {
                exit 0
              } else {
                exit 1
              }
            } else {
              print "Invalid power value"
              exit 1
            }
          }'

          status=$?
          if [[ $status -eq 0 ]]; then
            echo "Power value is in the expected range [$min, $max]."
          else
            echo "Power value is outside the expected range [$min, $max]."
            exit 1
          fi

      - name: Validate grid intensity
        shell: bash
        run: |
          if ! grep -q "472 gCO₂eq/kWh" /tmp/eco-ci/output.txt; then
            echo "Carbon intensity 472 gCO₂eq/kWh not found in /tmp/eco-ci/output.txt"
            exit 1
          fi
